//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServices.EntityFramework.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEM_BurialApplication_Deceased_Details
    {
        public long Id { get; set; }
        public long BurialApplicationId { get; set; }
        public string BINumber { get; set; }
        public string Name { get; set; }
        public string BurialOrderNumber { get; set; }
    }
}
