//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServices.EntityFramework.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEM_LIST_CEMETERY_SUPERVISOR
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string SupervisorPassword { get; set; }
        public Nullable<long> CemeteryId { get; set; }
    }
}
