//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServices.EntityFramework.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEM_LIST_CEMETERY
    {
        public long ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> RECYCLEYEARS { get; set; }
        public Nullable<int> RECYCLEGRAVES { get; set; }
        public Nullable<long> CURRENTCAPACITY { get; set; }
        public Nullable<decimal> LATTITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<long> TOTALCAPACITY { get; set; }
        public string SURNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string TITLE { get; set; }
        public string TELWORK { get; set; }
        public string TELCELL { get; set; }
        public string EMAIL { get; set; }
        public string STREET { get; set; }
        public string SUBURB { get; set; }
        public Nullable<long> CITYID { get; set; }
        public string POSTALCODE { get; set; }
        public string CREMATORIUM { get; set; }
        public Nullable<decimal> LEASERENEWAL { get; set; }
        public byte[] LastEditDate { get; set; }
        public Nullable<long> CreationDate { get; set; }
        public Nullable<int> MAXBURIALS { get; set; }
        public string MAXBURIALSFlag { get; set; }
        public Nullable<long> CATEGORYID { get; set; }
        public string VoteNumber { get; set; }
        public Nullable<int> IsEnviromentalHealth { get; set; }
    }
}
