//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServices.EntityFramework.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEM_LIST_UNDERTAKER
    {
        public long ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Cell { get; set; }
        public string Fax { get; set; }
        public string Title { get; set; }
        public string Initial { get; set; }
        public string FirstN { get; set; }
        public string Surn { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> Active { get; set; }
        public string DesignationNumber { get; set; }
        public Nullable<System.DateTime> ComplianceDate { get; set; }
        public string VATNumber { get; set; }
        public string REGNumber { get; set; }
        public string PostalAddress { get; set; }
        public Nullable<int> MaxBodyCapacity { get; set; }
        public string IDNumber { get; set; }
        public string PortalUsername { get; set; }
        public string PortalContactNumber { get; set; }
        public string PortalEmailAddress { get; set; }
        public Nullable<int> GrantAccess { get; set; }
        public string WebPortalNotice { get; set; }
        public string PortalOtp { get; set; }
        public Nullable<int> IsMonumentalCompany { get; set; }
    }
}
